In [ ]:
#importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#Importing Dataset and Deleting missing rows
dataset = pd.read_csv('Loan Approval.csv')
dataset = dataset.dropna()

In [ ]:
dataset.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
#Dependent Data initialization
y = dataset.iloc[:, -1].values

In [ ]:
#X[ : , 1:2] = X[ : , 1:2].reshape(480)
y.shape

(480,)

In [ ]:
#Independent Data Initialisation
#Converting Categorical variables to numbers
obj_df = dataset
obj_df.head

<bound method NDFrame.head of       Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
1    LP001003    Male     Yes  ...            1.0         Rural           N
2    LP001005    Male     Yes  ...            1.0         Urban           Y
3    LP001006    Male     Yes  ...            1.0         Urban           Y
4    LP001008    Male      No  ...            1.0         Urban           Y
5    LP001011    Male     Yes  ...            1.0         Urban           Y
..        ...     ...     ...  ...            ...           ...         ...
609  LP002978  Female      No  ...            1.0         Rural           Y
610  LP002979    Male     Yes  ...            1.0         Rural           Y
611  LP002983    Male     Yes  ...            1.0         Urban           Y
612  LP002984    Male     Yes  ...            1.0         Urban           Y
613  LP002990  Female      No  ...            0.0     Semiurban           N

[480 rows x 13 columns]>

In [ ]:
#Gender_Column(Male- 1, Female- 0)
obj_df["Gender"] = obj_df["Gender"].astype('category')
obj_df["Gender_cat"] =obj_df["Gender"].cat.codes
obj_df.head()

Loan_ID Gender Married  ... Property_Area Loan_Status Gender_cat
1  LP001003   Male     Yes  ...         Rural           N          1
2  LP001005   Male     Yes  ...         Urban           Y          1
3  LP001006   Male     Yes  ...         Urban           Y          1
4  LP001008   Male      No  ...         Urban           Y          1
5  LP001011   Male     Yes  ...         Urban           Y          1

[5 rows x 14 columns]

In [ ]:
#Married Column (Yes- 1,No- 0)
obj_df["Married"] = obj_df["Married"].astype('category')
obj_df["Married_cat"] = obj_df["Married"].cat.codes
obj_df.head()

Loan_ID Gender Married  ... Loan_Status Gender_cat Married_cat
1  LP001003   Male     Yes  ...           N          1           1
2  LP001005   Male     Yes  ...           Y          1           1
3  LP001006   Male     Yes  ...           Y          1           1
4  LP001008   Male      No  ...           Y          1           0
5  LP001011   Male     Yes  ...           Y          1           1

[5 rows x 15 columns]

In [ ]:
#Education(Graduate- 0 , Non-Graduate- 1 )
obj_df["Education"] = obj_df["Education"].astype('category')
obj_df["Education_cat"] = obj_df["Education"].cat.codes
obj_df.head()

Loan_ID Gender Married  ... Gender_cat Married_cat Education_cat
1  LP001003   Male     Yes  ...          1           1             0
2  LP001005   Male     Yes  ...          1           1             0
3  LP001006   Male     Yes  ...          1           1             1
4  LP001008   Male      No  ...          1           0             0
5  LP001011   Male     Yes  ...          1           1             0

[5 rows x 16 columns]

In [ ]:
#Self_Employed (No- 0 ,Yes- 1) 
obj_df["Self_Employed"] = obj_df["Self_Employed"].astype('category')
obj_df["Self_Employed_cat"] = obj_df["Self_Employed"].cat.codes
obj_df.head()

Loan_ID Gender Married  ... Married_cat Education_cat Self_Employed_cat
1  LP001003   Male     Yes  ...           1             0                 0
2  LP001005   Male     Yes  ...           1             0                 1
3  LP001006   Male     Yes  ...           1             1                 0
4  LP001008   Male      No  ...           0             0                 0
5  LP001011   Male     Yes  ...           1             0                 1

[5 rows x 17 columns]

In [ ]:
#Property Area (Rural - 0 ,Semi urban - 1 , Urban - 2) 
obj_df["Property_Area"] = obj_df["Property_Area"].astype('category')
obj_df["Property_Area_cat"] = obj_df["Property_Area"].cat.codes
obj_df.head()

Loan_ID Gender Married  ... Education_cat Self_Employed_cat Property_Area_cat
1  LP001003   Male     Yes  ...             0                 0                 0
2  LP001005   Male     Yes  ...             0                 1                 2
3  LP001006   Male     Yes  ...             1                 0                 2
4  LP001008   Male      No  ...             0                 0                 2
5  LP001011   Male     Yes  ...             0                 1                 2

[5 rows x 18 columns]

In [ ]:
#Dropping Columns
X =  obj_df.drop(['Loan_ID' , 'Loan_Status' , 'Gender' ,'Married','Education' , 'Self_Employed' , 'Property_Area' ] , axis= 1)
X

Dependents  ApplicantIncome  ...  Self_Employed_cat  Property_Area_cat
1            1             4583  ...                  0                  0
2            0             3000  ...                  1                  2
3            0             2583  ...                  0                  2
4            0             6000  ...                  0                  2
5            2             5417  ...                  1                  2
..         ...              ...  ...                ...                ...
609          0             2900  ...                  0                  0
610         3+             4106  ...                  0                  0
611          1             8072  ...                  0                  2
612          2             7583  ...                  0                  2
613          0             4583  ...                  1                  1

[480 rows x 11 columns]

In [ ]:
#Renaming Columns
X.rename(columns = {'Gender_cat':'Gender', 'Married_cat':'Married', 
                              'Education_cat':'Education' ,'Self_Employed_cat':'Self_Employed','Property_Area_cat':'Property_Area' }, inplace = True) 
print(X.columns)

Index(['Dependents', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Gender', 'Married', 'Education',
       'Self_Employed', 'Property_Area'],
      dtype='object')


In [ ]:
X

Dependents  ApplicantIncome  ...  Self_Employed  Property_Area
1            1             4583  ...              0              0
2            0             3000  ...              1              2
3            0             2583  ...              0              2
4            0             6000  ...              0              2
5            2             5417  ...              1              2
..         ...              ...  ...            ...            ...
609          0             2900  ...              0              0
610         3+             4106  ...              0              0
611          1             8072  ...              0              2
612          2             7583  ...              0              2
613          0             4583  ...              1              1

[480 rows x 11 columns]

In [ ]:
X.dtypes

Dependents            object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Gender                  int8
Married                 int8
Education               int8
Self_Employed           int8
Property_Area           int8
dtype: object

In [ ]:
#Removing Special Characters from the Columns and Changing its datatype to int
X=X.replace('\+','',regex=True).astype(int)
X

Dependents  ApplicantIncome  ...  Self_Employed  Property_Area
1             1             4583  ...              0              0
2             0             3000  ...              1              2
3             0             2583  ...              0              2
4             0             6000  ...              0              2
5             2             5417  ...              1              2
..          ...              ...  ...            ...            ...
609           0             2900  ...              0              0
610           3             4106  ...              0              0
611           1             8072  ...              0              2
612           2             7583  ...              0              2
613           0             4583  ...              1              1

[480 rows x 11 columns]

In [ ]:
X.dtypes

Dependents           int64
ApplicantIncome      int64
CoapplicantIncome    int64
LoanAmount           int64
Loan_Amount_Term     int64
Credit_History       int64
Gender               int64
Married              int64
Education            int64
Self_Employed        int64
Property_Area        int64
dtype: object

In [ ]:
#Standardising X data
from sklearn.preprocessing import StandardScaler
scl = StandardScaler()
scl.fit(X)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X = pd.DataFrame(scl.transform(X))
X

0         1         2   ...        8         9         10
0    0.218599 -0.137970 -0.027951  ... -0.503253 -0.399275 -1.318868
1   -0.762033 -0.417536 -0.604632  ... -0.503253  2.504541  1.259774
2   -0.762033 -0.491180  0.297101  ...  1.987072 -0.399275  1.259774
3   -0.762033  0.112280 -0.604632  ... -0.503253 -0.399275  1.259774
4    1.199231  0.009319  0.999978  ... -0.503253  2.504541  1.259774
..        ...       ...       ...  ...       ...       ...       ...
475 -0.762033 -0.435196 -0.604632  ... -0.503253 -0.399275 -1.318868
476  2.179863 -0.222210 -0.604632  ... -0.503253 -0.399275 -1.318868
477  0.218599  0.478206 -0.512853  ... -0.503253 -0.399275  1.259774
478  1.199231  0.391846 -0.604632  ... -0.503253 -0.399275  1.259774
479 -0.762033 -0.137970 -0.604632  ... -0.503253  2.504541 -0.029547

[480 rows x 11 columns]

In [ ]:
X

0         1         2   ...        8         9         10
0    0.218599 -0.137970 -0.027951  ... -0.503253 -0.399275 -1.318868
1   -0.762033 -0.417536 -0.604632  ... -0.503253  2.504541  1.259774
2   -0.762033 -0.491180  0.297101  ...  1.987072 -0.399275  1.259774
3   -0.762033  0.112280 -0.604632  ... -0.503253 -0.399275  1.259774
4    1.199231  0.009319  0.999978  ... -0.503253  2.504541  1.259774
..        ...       ...       ...  ...       ...       ...       ...
475 -0.762033 -0.435196 -0.604632  ... -0.503253 -0.399275 -1.318868
476  2.179863 -0.222210 -0.604632  ... -0.503253 -0.399275 -1.318868
477  0.218599  0.478206 -0.512853  ... -0.503253 -0.399275  1.259774
478  1.199231  0.391846 -0.604632  ... -0.503253 -0.399275  1.259774
479 -0.762033 -0.137970 -0.604632  ... -0.503253  2.504541 -0.029547

[480 rows x 11 columns]

In [ ]:
#Label Encoding Y value
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,

In [ ]:
y = y.reshape(480,1)
y.shape

(480, 1)

In [ ]:
X.shape

(480, 11)

In [ ]:
#Logistics Regression

In [ ]:
#Spilitting of dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
#Fitting Logistics Regsression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#Confusion matrix
y_pre = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pre)
print(cm)
accuracy_score(y_test, y_pre)

[[15 27]
 [ 0 78]]


0.775

In [ ]:
#Comparing y test and y pred results
y_pre_yts =np.concatenate((y_pre.reshape(len(y_pre),1), y_test.reshape(len(y_test),1)),1)

In [ ]:
#Finding Y value using Logistic Regression
print(classifier.predict(scl.transform([[2 ,	5417 , 	4196 , 	267 ,	360 ,	1,1,1	,0,	1,	2]])))

[1]


In [ ]:
#Evaluating Train and Test Accuracy
print(classifier.score(X_train,y_train))
print(classifier.score(X_test,y_test))

0.8166666666666667
0.775


In [ ]:
#Decision tree classification

In [ ]:
#Fitting Decision Tree Classification model
from sklearn.tree import DecisionTreeClassifier
DecisionTree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DecisionTree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
#Finding no of rows in train and test data
print(len(X_train))
print(len(X_test))

360
120


In [ ]:
#Confusion matrix between ytest and ypred
y_pred = DecisionTree.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[21 21]
 [18 60]]


0.675

In [ ]:
#Finding Y value using Logistic Regression
print(DecisionTree.predict(scl.transform([[2 ,	5417 , 	4196 , 	267 ,	360 ,	1,1,1	,0,	1,	2]])))


[1]


In [ ]:
#Comparing y test and y pred esults
y_pre_yts =np.concatenate((y_pre.reshape(len(y_pre),1), y_test.reshape(len(y_test),1)),1)

In [ ]:
#Evaluating Train and Test Accuracy
print(DecisionTree.score(X_train,y_train))
print(DecisionTree.score(X_test,y_test))

1.0
0.675


In [ ]:
#Random_forest classification

In [ ]:
#Fitting Random forest Classification model
from sklearn.ensemble import RandomForestClassifier
RandomForest = RandomForestClassifier(n_estimators = 115, criterion = 'entropy', random_state = 0)
RandomForest.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=115,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
#Confusion matrix between ytest and ypred
y_pred = RandomForest.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17 25]
 [ 1 77]]


0.7833333333333333

In [ ]:
#Comparing y test and y pred results

ypp = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

In [ ]:
#Finding Y value using Logistic Regression
print(RandomForest.predict(scl.transform([[2 ,	5417 , 	4196 , 	267 ,	360 ,	1,1,1	,0,	1,	2]])))


[1]


In [ ]:
#Evaluating Train and Test Accuracy
print(RandomForest.score(X_train,y_train))
print(RandomForest.score(X_test,y_test))

1.0
0.7833333333333333
